// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sorcha.Wallet.Core.Data;

#nullable disable

namespace Sorcha.Wallet.Core.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260226230802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wallet")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.CredentialEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClaimsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuanceBlueprintId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IssuanceTxId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuerDid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaxPresentations")
                        .HasColumnType("integer");

                    b.Property<int>("PresentationCount")
                        .HasColumnType("integer");

                    b.Property<string>("RawToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<int?>("StatusListIndex")
                        .HasColumnType("integer");

                    b.Property<string>("StatusListUrl")
                        .HasColumnType("text");

                    b.Property<string>("SubjectDid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UsagePolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IssuerDid")
                        .HasDatabaseName("IX_Credentials_IssuerDid");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Credentials_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Credentials_Type");

                    b.HasIndex("WalletAddress")
                        .HasDatabaseName("IX_Credentials_WalletAddress");

                    b.HasIndex("WalletAddress", "Type")
                        .HasDatabaseName("IX_Credentials_Wallet_Type");

                    b.ToTable("Credentials", "wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasComment("Wallet address in Bech32m format (ws1...). Variable length by algorithm: ED25519 ~66 chars, NISTP256 ~107 chars, RSA4096 ~700 chars.");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("EncryptionKeyId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("LastAccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<Dictionary<string, string>>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Address");

                    b.HasIndex("Owner")
                        .HasDatabaseName("IX_Wallets_Owner");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Wallets_Status");

                    b.HasIndex("Tenant")
                        .HasDatabaseName("IX_Wallets_Tenant");

                    b.HasIndex("Owner", "Tenant")
                        .HasDatabaseName("IX_Wallets_Owner_Tenant");

                    b.HasIndex("Tenant", "Status")
                        .HasDatabaseName("IX_Wallets_Tenant_Status");

                    b.ToTable("Wallets", "wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.WalletAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessRight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentWalletAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ParentWalletAddress")
                        .HasDatabaseName("IX_WalletAccess_ParentWalletAddress");

                    b.HasIndex("Subject")
                        .HasDatabaseName("IX_WalletAccess_Subject");

                    b.HasIndex("ParentWalletAddress", "Subject")
                        .HasDatabaseName("IX_WalletAccess_Parent_Subject");

                    b.HasIndex("Subject", "RevokedAt")
                        .HasDatabaseName("IX_WalletAccess_Subject_Active");

                    b.ToTable("WalletAccess", "wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.WalletAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("Account")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DerivationPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("FirstUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChange")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ParentWalletAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Tags")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasDatabaseName("IX_WalletAddresses_Address");

                    b.HasIndex("ParentWalletAddress")
                        .HasDatabaseName("IX_WalletAddresses_ParentWalletAddress");

                    b.HasIndex("ParentWalletAddress", "Index")
                        .HasDatabaseName("IX_WalletAddresses_Parent_Index");

                    b.HasIndex("ParentWalletAddress", "Account", "IsChange", "Index")
                        .HasDatabaseName("IX_WalletAddresses_Derivation");

                    b.ToTable("WalletAddresses", "wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(28, 18)
                        .HasColumnType("numeric(28,18)");

                    b.Property<long?>("BlockHeight")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ParentWalletAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawTransaction")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WalletTransactions_CreatedAt");

                    b.HasIndex("ParentWalletAddress")
                        .HasDatabaseName("IX_WalletTransactions_ParentWalletAddress");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_WalletTransactions_State");

                    b.HasIndex("ParentWalletAddress", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_WalletTransactions_Parent_CreatedAt");

                    b.HasIndex("ParentWalletAddress", "State")
                        .HasDatabaseName("IX_WalletTransactions_Parent_State");

                    b.ToTable("WalletTransactions", "wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.WalletAccess", b =>
                {
                    b.HasOne("Sorcha.Wallet.Core.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Delegates")
                        .HasForeignKey("ParentWalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.WalletAddress", b =>
                {
                    b.HasOne("Sorcha.Wallet.Core.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Addresses")
                        .HasForeignKey("ParentWalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Sorcha.Wallet.Core.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("ParentWalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Sorcha.Wallet.Core.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Delegates");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
