openapi: 3.1.0
info:
  title: Participant Identity API
  description: API for managing participant identities, wallet linking, and participant discovery
  version: 1.0.0
  contact:
    name: Sorcha Team

servers:
  - url: /api/v1
    description: Tenant Service API

tags:
  - name: Participants
    description: Participant identity management
  - name: Wallet Linking
    description: Wallet address linking and verification
  - name: Search
    description: Participant discovery and search

paths:
  /organizations/{organizationId}/participants:
    post:
      operationId: createParticipant
      summary: Register a user as a participant
      description: Admin registers an existing organization user as a participant, or user self-registers
      tags: [Participants]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateParticipantRequest'
      responses:
        '201':
          description: Participant created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          description: User is already a participant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      operationId: listParticipants
      summary: List participants in an organization
      description: Returns paginated list of participants for the organization
      tags: [Participants]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/ParticipantStatus'
        - name: includeInactive
          in: query
          schema:
            type: boolean
            default: false
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: Paginated list of participants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /organizations/{organizationId}/participants/{participantId}:
    get:
      operationId: getParticipant
      summary: Get participant details
      description: Returns detailed information about a specific participant
      tags: [Participants]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - $ref: '#/components/parameters/ParticipantId'
      responses:
        '200':
          description: Participant details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantDetailResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      operationId: updateParticipant
      summary: Update participant details
      description: Update participant display name or status
      tags: [Participants]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - $ref: '#/components/parameters/ParticipantId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateParticipantRequest'
      responses:
        '200':
          description: Participant updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      operationId: deactivateParticipant
      summary: Deactivate a participant
      description: Soft-delete participant (preserves for audit)
      tags: [Participants]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - $ref: '#/components/parameters/ParticipantId'
      responses:
        '204':
          description: Participant deactivated
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /organizations/{organizationId}/participants/{participantId}/wallet-links:
    post:
      operationId: initiateWalletLink
      summary: Initiate wallet address linking
      description: Generate a challenge for wallet address verification
      tags: [Wallet Linking]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - $ref: '#/components/parameters/ParticipantId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateWalletLinkRequest'
      responses:
        '200':
          description: Challenge generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletLinkChallengeResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          description: Address already linked to another participant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      operationId: listWalletLinks
      summary: List linked wallet addresses
      description: Returns all wallet addresses linked to the participant
      tags: [Wallet Linking]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - $ref: '#/components/parameters/ParticipantId'
        - name: includeRevoked
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of linked wallet addresses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletLinkListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /organizations/{organizationId}/participants/{participantId}/wallet-links/{challengeId}/verify:
    post:
      operationId: verifyWalletLink
      summary: Complete wallet linking verification
      description: Submit signed challenge to complete wallet address linking
      tags: [Wallet Linking]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - $ref: '#/components/parameters/ParticipantId'
        - name: challengeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyWalletLinkRequest'
      responses:
        '200':
          description: Wallet address linked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkedWalletAddressResponse'
        '400':
          description: Invalid signature or expired challenge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /organizations/{organizationId}/participants/{participantId}/wallet-links/{linkId}:
    delete:
      operationId: revokeWalletLink
      summary: Revoke a wallet address link
      description: Soft-delete wallet link (preserves for audit, releases address)
      tags: [Wallet Linking]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrganizationId'
        - $ref: '#/components/parameters/ParticipantId'
        - name: linkId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Wallet link revoked
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /participants/search:
    post:
      operationId: searchParticipants
      summary: Search participants across organizations
      description: Search participants by name, email, or wallet address (respects org visibility)
      tags: [Search]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParticipantSearchRequest'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantSearchResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /participants/by-wallet/{walletAddress}:
    get:
      operationId: getParticipantByWallet
      summary: Lookup participant by wallet address
      description: Find the participant linked to a specific wallet address
      tags: [Search]
      security:
        - bearerAuth: []
      parameters:
        - name: walletAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Participant found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: No participant linked to this address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /me/participant-profiles:
    get:
      operationId: getMyParticipantProfiles
      summary: Get current user's participant profiles
      description: Returns all participant identities for the authenticated user across organizations
      tags: [Participants]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User's participant profiles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyParticipantProfilesResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    OrganizationId:
      name: organizationId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    ParticipantId:
      name: participantId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    PageNumber:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1
    PageSize:
      name: pageSize
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  schemas:
    ParticipantStatus:
      type: string
      enum: [Active, Inactive, Suspended]

    WalletLinkStatus:
      type: string
      enum: [Active, Revoked]

    ChallengeStatus:
      type: string
      enum: [Pending, Completed, Expired, Failed]

    CreateParticipantRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          format: uuid
          description: User ID from Tenant Service (omit for self-registration)
        displayName:
          type: string
          maxLength: 256
          description: Display name (defaults to user's name)

    UpdateParticipantRequest:
      type: object
      properties:
        displayName:
          type: string
          maxLength: 256
        status:
          $ref: '#/components/schemas/ParticipantStatus'

    ParticipantResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        organizationId:
          type: string
          format: uuid
        organizationName:
          type: string
        displayName:
          type: string
        email:
          type: string
        status:
          $ref: '#/components/schemas/ParticipantStatus'
        hasLinkedWallet:
          type: boolean
        createdAt:
          type: string
          format: date-time

    ParticipantDetailResponse:
      allOf:
        - $ref: '#/components/schemas/ParticipantResponse'
        - type: object
          properties:
            linkedWallets:
              type: array
              items:
                $ref: '#/components/schemas/LinkedWalletAddressResponse'
            updatedAt:
              type: string
              format: date-time

    ParticipantListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantResponse'
        totalCount:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer
        totalPages:
          type: integer

    InitiateWalletLinkRequest:
      type: object
      required:
        - walletAddress
      properties:
        walletAddress:
          type: string
          maxLength: 256
          description: Wallet address to link

    WalletLinkChallengeResponse:
      type: object
      properties:
        challengeId:
          type: string
          format: uuid
        challenge:
          type: string
          description: Message to sign with wallet private key
        expiresAt:
          type: string
          format: date-time
        walletAddress:
          type: string

    VerifyWalletLinkRequest:
      type: object
      required:
        - signature
        - publicKey
      properties:
        signature:
          type: string
          format: byte
          description: Base64-encoded signature of challenge
        publicKey:
          type: string
          format: byte
          description: Base64-encoded public key

    LinkedWalletAddressResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        walletAddress:
          type: string
        algorithm:
          type: string
        status:
          $ref: '#/components/schemas/WalletLinkStatus'
        linkedAt:
          type: string
          format: date-time
        revokedAt:
          type: string
          format: date-time
          nullable: true

    WalletLinkListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LinkedWalletAddressResponse'
        totalCount:
          type: integer

    ParticipantSearchRequest:
      type: object
      properties:
        query:
          type: string
          description: Search term (name, email, or wallet address)
        organizationId:
          type: string
          format: uuid
          description: Filter by organization (optional)
        status:
          $ref: '#/components/schemas/ParticipantStatus'
        hasLinkedWallet:
          type: boolean
        page:
          type: integer
          default: 1
        pageSize:
          type: integer
          default: 20
          maximum: 100

    ParticipantSearchResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantResponse'
        totalCount:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer

    MyParticipantProfilesResponse:
      type: object
      properties:
        profiles:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantDetailResponse'

    ErrorResponse:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

  responses:
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              type:
                type: string
              title:
                type: string
              status:
                type: integer
              errors:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
