openapi: 3.1.0
info:
  title: Sorcha Tenant Service - Administration API
  version: 1.0.0
  description: |
    Organization and IDP configuration management endpoints.
    Requires administrator role for all operations.

servers:
  - url: https://tenant.sorcha.io/api/admin
    description: Production
  - url: https://localhost:7080/api/admin
    description: Local Development

tags:
  - name: Organizations
    description: Organization lifecycle management
  - name: Identity Providers
    description: External IDP configuration
  - name: Permissions
    description: Organization-level permissions

security:
  - BearerAuth: []

paths:
  /organizations:
    post:
      summary: Create new organization
      description: Creates organization, schema, and assigns creator as administrator
      tags: [Organizations]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 200
                  example: Acme Corporation
                subdomain:
                  type: string
                  pattern: '^[a-z0-9-]{3,50}$'
                  example: acme
                branding:
                  type: object
                  properties:
                    logoUrl:
                      type: string
                      format: uri
                    primaryColor:
                      type: string
                      pattern: '^#[0-9A-Fa-f]{6}$'
                    secondaryColor:
                      type: string
                      pattern: '^#[0-9A-Fa-f]{6}$'
              required: [name, subdomain]
      responses:
        '201':
          description: Organization created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: Subdomain already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: List organizations
      description: Lists all organizations (global admin only)
      tags: [Organizations]
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [Active, Suspended, Deleted]
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Organization list
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Organization'
                  total:
                    type: integer
                  page:
                    type: integer
                  page_size:
                    type: integer

  /organizations/{orgId}:
    get:
      summary: Get organization details
      tags: [Organizations]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
      responses:
        '200':
          description: Organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update organization
      tags: [Organizations]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                status:
                  type: string
                  enum: [Active, Suspended, Deleted]
                branding:
                  type: object
      responses:
        '200':
          description: Organization updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'

  /organizations/{orgId}/idp:
    put:
      summary: Configure external IDP
      tags: [Identity Providers]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdpConfiguration'
      responses:
        '200':
          description: IDP configured
        '400':
          description: Invalid IDP configuration

    get:
      summary: Get IDP configuration
      tags: [Identity Providers]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
      responses:
        '200':
          description: IDP configuration (secrets redacted)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdpConfiguration'

    delete:
      summary: Remove IDP configuration
      tags: [Identity Providers]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
      responses:
        '204':
          description: IDP removed

  /organizations/{orgId}/permissions:
    put:
      summary: Update organization permissions
      tags: [Permissions]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                approvedBlockchains:
                  type: array
                  items:
                    type: string
                    format: uuid
                canCreateBlockchain:
                  type: boolean
                canPublishBlueprint:
                  type: boolean
      responses:
        '200':
          description: Permissions updated

    get:
      summary: Get organization permissions
      tags: [Permissions]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
      responses:
        '200':
          description: Current permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  approvedBlockchains:
                    type: array
                    items:
                      type: string
                  canCreateBlockchain:
                    type: boolean
                  canPublishBlueprint:
                    type: boolean

  /organizations/{orgId}/users:
    get:
      summary: List organization users
      tags: [Organizations]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
        - name: role
          in: query
          schema:
            type: string
            enum: [Administrator, Auditor, Member]
      responses:
        '200':
          description: User list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserIdentity'

  /organizations/{orgId}/users/{userId}/roles:
    put:
      summary: Update user roles
      tags: [Organizations]
      parameters:
        - $ref: '#/components/parameters/OrgIdPath'
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roles:
                  type: array
                  items:
                    type: string
                    enum: [Administrator, Auditor, Member]
      responses:
        '200':
          description: Roles updated

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    OrgIdPath:
      name: orgId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    Organization:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        subdomain:
          type: string
        status:
          type: string
          enum: [Active, Suspended, Deleted]
        createdAt:
          type: string
          format: date-time
        branding:
          type: object
          properties:
            logoUrl:
              type: string
              format: uri
            primaryColor:
              type: string
            secondaryColor:
              type: string

    IdpConfiguration:
      type: object
      properties:
        providerType:
          type: string
          enum: [AzureEntra, AwsCognito, GenericOidc]
        issuerUrl:
          type: string
          format: uri
        clientId:
          type: string
        clientSecret:
          type: string
          writeOnly: true
        scopes:
          type: array
          items:
            type: string
        metadataUrl:
          type: string
          format: uri
      required: [providerType, issuerUrl, clientId, clientSecret, scopes]

    UserIdentity:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        displayName:
          type: string
        roles:
          type: array
          items:
            type: string
        status:
          type: string
        lastLoginAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
