openapi: 3.1.0
info:
  title: Sorcha Tenant Service - Audit API
  version: 1.0.0
  description: Audit log query endpoints for compliance and security monitoring

servers:
  - url: https://tenant.sorcha.io/api/audit
    description: Production
  - url: https://localhost:7080/api/audit
    description: Local Development

security:
  - BearerAuth: []

paths:
  /logs:
    get:
      summary: Query audit logs
      description: Retrieve audit logs filtered by criteria (requires Administrator or Auditor role)
      parameters:
        - name: event_type
          in: query
          schema:
            type: string
            enum: [Login, Logout, TokenIssued, TokenRevoked, PermissionDenied]
        - name: identity_id
          in: query
          schema:
            type: string
            format: uuid
        - name: start_date
          in: query
          schema:
            type: string
            format: date-time
        - name: end_date
          in: query
          schema:
            type: string
            format: date-time
        - name: success
          in: query
          schema:
            type: boolean
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
      responses:
        '200':
          description: Audit log entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AuditLogEntry'
                  total:
                    type: integer
                  page:
                    type: integer

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuditLogEntry:
      type: object
      properties:
        id:
          type: integer
        timestamp:
          type: string
          format: date-time
        eventType:
          type: string
        identityId:
          type: string
          format: uuid
        ipAddress:
          type: string
        userAgent:
          type: string
        success:
          type: boolean
        details:
          type: object
