#!/usr/bin/env pwsh
# Wallet Encryption Keys Backup Script
# Generated by setup-wallet-encryption-docker.ps1

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupDir = "./backups/wallet-keys"
$backupFile = "wallet-keys-$timestamp.tar.gz"

# Create backup directory
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null

# Backup encryption keys
Write-Host "Backing up wallet encryption keys..."
docker run --rm `
  -v wallet-encryption-keys:/source:ro `
  -v "$PWD/$backupDir:/backup" `
  alpine `
  tar czf /backup/$backupFile -C /source .

if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Backup created: $backupDir/$backupFile" -ForegroundColor Green

    # Show backup size
    $size = (Get-Item "$backupDir/$backupFile").Length
    Write-Host "  Size: $($size / 1KB) KB"
} else {
    Write-Host "✗ Backup failed" -ForegroundColor Red
    exit 1
}
