#!/usr/bin/env pwsh
# Wallet Encryption Keys Restore Script
# Generated by setup-wallet-encryption-docker.ps1

param(
    [Parameter(Mandatory=$true)]
    [string]$BackupFile
)

if (-not (Test-Path $BackupFile)) {
    Write-Host "✗ Backup file not found: $BackupFile" -ForegroundColor Red
    exit 1
}

Write-Host "⚠ WARNING: This will replace all existing encryption keys" -ForegroundColor Yellow
Write-Host "  Backup file: $BackupFile"
Write-Host ""
$confirm = Read-Host "Type 'RESTORE' to confirm"

if ($confirm -ne "RESTORE") {
    Write-Host "Restore cancelled"
    exit 0
}

# Stop wallet service
Write-Host "Stopping wallet service..."
docker compose stop wallet-service

# Restore keys
Write-Host "Restoring encryption keys..."
docker run --rm `
  -v wallet-encryption-keys:/target `
  -v "$PWD/backups/wallet-keys:/backup:ro" `
  alpine `
  tar xzf /backup/$(Split-Path $BackupFile -Leaf) -C /target

if ($LASTEXITCODE -eq 0) {
    Write-Host "✓ Restore complete" -ForegroundColor Green

    # Restart wallet service
    Write-Host "Restarting wallet service..."
    docker compose start wallet-service

    Write-Host "✓ Wallet service restarted" -ForegroundColor Green
} else {
    Write-Host "✗ Restore failed" -ForegroundColor Red
    exit 1
}
